import { Outfit } from "next/font/google";

import "./globals.css";
import { Providers } from "./providers";

import type { Metadata } from "next";
const outfit = Outfit({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`h-screen w-screen bg-slate-50 ${outfit.className}`}>
          {children}
        </body>
      </Providers>
    </html>
  );
}
