import { Open_Sans } from "next/font/google";

import "./globals.css";
import { Providers } from "./providers";

import type { Metadata } from "next";
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`h-screen w-screen p-4${openSans.className}`}>
          {children}
        </body>
      </Providers>
    </html>
  );
}
